apiVersion: v1
kind: Namespace
metadata:
  name: test-helmchart
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: sample
  namespace: test-helmchart
spec:
  interval: 5m0s
  chart: podinfo
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: sample
  version: '5.*'
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-helmchart
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: HelmChart
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
