apiVersion: v1
kind: Namespace
metadata:
  name: test-gitrepository
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample
  namespace: test-gitrepository
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-gitrepository
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
