apiVersion: v1
kind: Namespace
metadata:
  name: test-helmrepository
---
apiVersion: v1
kind: Secret
metadata:
  name: fake-secret
  namespace: test-helmrepository
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sample
  namespace: test-helmrepository
spec:
  interval: 5m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-helmrepository
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: HelmRepository
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
