apiVersion: v1
kind: Namespace
metadata:
  name: test-policy
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: sample
  namespace: test-policy
spec:
  validationFailureAction: Enforce
  rules:
  - name: require-pod-purpose-label
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "You must have label `purpose` with value `production` set on all new Pod in test-policy Namespace."
      pattern:
        metadata:
          labels:
            purpose: production
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-policy
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: kyverno.io/v1
      kind: Policy
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member2
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
