apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sample
spec:
  validationFailureAction: Enforce
  rules:
  - name: require-ns-purpose-label
    match:
      any:
      - resources:
          kinds:
          - Namespace
    validate:
      message: "You must have label `purpose` with value `production` set on all new namespaces."
      pattern:
        metadata:
          labels:
            purpose: production
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: sample
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: kyverno.io/v1
      kind: ClusterPolicy
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member2
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
