apiVersion: v1
kind: Namespace
metadata:
  name: test-kustomization
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample
  namespace: test-kustomization
spec:
  interval: 10m
  targetNamespace: test-kustomization
  sourceRef:
    kind: GitRepository
    name: sample
  path: "./kustomize"
  prune: true
  timeout: 1m
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-kustomization
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
