apiVersion: v1
kind: Namespace
metadata:
  name: test-bcj
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: mysql-config
  namespace: test-bcj
data:
  log: "1"
  lower: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-sample-config
  namespace: test-bcj
data:
  nginx.properties: |
    proxy-connect-timeout: "10s"
    proxy-read-timeout: "10s"
    client-max-body-size: "2m"
---
apiVersion: apps.kruise.io/v1alpha1
kind: BroadcastJob
metadata:
  labels:
    app: sample
  name: sample
  namespace: test-bcj
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: sample
    spec:
      restartPolicy: Never
      volumes:
        - name: configmap
          configMap:
            name: my-sample-config    
      containers:
        - name: nginx
          image: nginx:alpine
          env: 
          - name: logData
            valueFrom: 
              configMapKeyRef:
                name: mysql-config
                key: log
          - name: lowerData
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: lower
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 10
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-bcj
  labels:
    app: sample
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: apps.kruise.io/v1alpha1
      kind: BroadcastJob
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
