apiVersion: v1
kind: Namespace
metadata:
  name: test-helmrelease
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample
  namespace: test-helmrelease
spec:
  interval: 5m
  chart:
    spec:
      chart: "./charts/podinfo"
      version: ">=4.0.0 <5.0.0"
      sourceRef:
        kind: GitRepository
        name: sample
        namespace: test-helmrelease
      interval: 1m
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-helmrelease
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
