apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: declarative-configuration-gitrepository
spec:
  target:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
  customizations:
    healthInterpretation:
      luaScript: >
        function InterpretHealth(observedObj)
          if observedObj.status ~= nil and observedObj.status.conditions ~= nil then
            for conditionIndex = 1, #observedObj.status.conditions do
              if observedObj.status.conditions[conditionIndex].type == 'Ready' and observedObj.status.conditions[conditionIndex].status == 'True' and observedObj.status.conditions[conditionIndex].reason == 'Succeeded' then
                return true
              end
            end
          end
          return false
        end
    statusAggregation:
      luaScript: >
        function AggregateStatus(desiredObj, statusItems)
          if statusItems == nil then
            return desiredObj
          end
          if desiredObj.status == nil then
            desiredObj.status = {}
          end
          if desiredObj.status.conditions == nil then
            desiredObj.status.conditions = {}
          end
          artifact = {}
          lastHandledReconcileAt = ''
          conditions = {}          
          local conditionsIndex = 1
          for i = 1, #statusItems do
            if statusItems[i].status ~= nil and statusItems[i].status.artifact ~= nil then
              artifact = statusItems[i].status.artifact
            end
            if statusItems[i].status ~= nil and statusItems[i].status.lastHandledReconcileAt ~= nil then
              lastHandledReconcileAt = statusItems[i].status.lastHandledReconcileAt
            end
            if statusItems[i].status ~= nil and statusItems[i].status.conditions ~= nil then
              for conditionIndex = 1, #statusItems[i].status.conditions do
                statusItems[i].status.conditions[conditionIndex].message = statusItems[i].clusterName..': '..statusItems[i].status.conditions[conditionIndex].message
                conditions[conditionsIndex] = statusItems[i].status.conditions[conditionIndex]
                conditionsIndex = conditionsIndex + 1
              end
            end
          end
          desiredObj.status.observedGeneration = desiredObj.metadata.generation
          desiredObj.status.artifact = artifact
          desiredObj.status.lastHandledReconcileAt = lastHandledReconcileAt
          desiredObj.status.conditions = conditions
          return desiredObj
        end
    retention:
      luaScript: >
        function Retain(desiredObj, observedObj)
          if observedObj.spec.suspend ~= nil then
            desiredObj.spec.suspend = observedObj.spec.suspend
          end
          return desiredObj
        end
    statusReflection:
      luaScript: >
        function ReflectStatus (observedObj)
          status = {}
          if observedObj == nil or observedObj.status == nil then 
            return status
          end
          status.conditions = observedObj.status.conditions
          status.artifact = observedObj.status.artifact
          status.observedIgnore = observedObj.status.observedIgnore
          status.observedRecurseSubmodules = observedObj.status.observedRecurseSubmodules
          status.lastHandledReconcileAt = observedObj.status.lastHandledReconcileAt
          return status
        end
    dependencyInterpretation:
      luaScript: >
        function GetDependencies(desiredObj)
          dependentSecrets = {}
          refs = {}
          local idx = 1
          if desiredObj.spec.secretRef ~= nil and desiredObj.spec.secretRef.name ~= '' then
            dependentSecrets[desiredObj.spec.secretRef.name] = true
          end
          for key, value in pairs(dependentSecrets) do
            dependObj = {}
            dependObj.apiVersion = 'v1'
            dependObj.kind = 'Secret'
            dependObj.name = key
            dependObj.namespace = desiredObj.metadata.namespace
            refs[idx] = dependObj
            idx = idx + 1
          end
          return refs
        end
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-helmrelease
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample
  namespace: test-helmrelease
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-helmrelease
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
