apiVersion: v1
kind: Namespace
metadata:
  name: test-cleanuppolicy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: test-cleanuppolicy
  labels:
    canremove: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: nginx:latest
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-cleanuppolicy
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member2
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
