apiVersion: v1
kind: Namespace
metadata:
  name: test-workflow
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    app: sample
  name: sample
  namespace: test-workflow
spec:
  parallelism: 1
  entrypoint: example
  tolerations:
  - key: 'key'
    operation: 'Equal'
    value: 'value'
    effect: 'NoSchedule'

  templates:
  - name: example
    steps:
    - - name: hello
        template: whalesay

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample
  namespace: test-workflow
  labels:
    app: sample
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      name: sample
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
